article/urls.py
from django.contrib import admin
from django.urls import path
from article import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "article"

urlpatterns = [
    path('/login',views.login_user,name="login"),
    path('/logout',views.logout_user,name="logout"),
    path('/dashboard',views.dashboard,name="dashboard"),
    path('/panel',views.panel,name="panel"),
    path('/',views.blog,name="blog"),
    path('/article/<int:id>',views.article,name="article"),
] 

club/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Index,name="index"),
    path('test',views.test,name="test"),
    path('events',views.events,name="events"),
    path('contact',include("contact.urls")),
    path('blog',include("article.urls")),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.contrib import admin
from django.urls import path
from contact import views


app_name = "contacts"

urlpatterns = [
    path('',views.contact,name="contact"),
    path('/newmember',views.new_member,name="new member"),
] 

event/urls.py
from django.contrib import admin
from django.urls import path
from event import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "event"

urlpatterns = [
    path('/',views.events,name="events"),
    path('/<int:id>',views.event,name="event"),
    path('/<int:id>/sponsors',views.event_sponsors,name="event_sponsors"),
    path('/<int:id>/speakers',views.event_speakers,name="event_speakers"),
    path('/<int:id>/join',views.event_join,name="event_join"),
] 

templates/includes/carousel.html
{% load static %}
<div class="w-100 h-75">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100 h-100 image-effect" src="{% static 'images/image1.jpg' %}" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
                <h1>Hello</h1>
                <h5>lorem ipsum sit amet</h5>
                <br><br><br>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100 h-100 image-effect" src="{% static 'images/image2.jpg' %}" alt="Second slide">
            <div class="carousel-caption d-none d-md-block">
                <h1>Hello</h1>
                <h5>lorem ipsum sit amet</h5>
                <br><br><br>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100 h-100 image-effect" src="{% static 'images/image5.jpg' %}" alt="Third slide">
            <div class="carousel-caption d-none d-md-block">
                <h1>Hello</h1>
                <h5>lorem ipsum sit amet</h5>
                <br><br><br>
            </div>
        </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
        </a>
    </div>
</div>

<!--<div class="container">
<div class="w-75 h-75">
    <div class="carousel slide" id="carouselExample" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'images/mediafile1.jpg' %}" alt="First Slide" class="d-block w-100 h-100">
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/mediafile2.jpg' %}" alt="Second Slide" class="d-block w-100 h-100">
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/mediafile3.jpg' %}" alt="Third Slide" class="d-block w-100 h-100">
            </div>
        </div>
    </div>
</div>
</div>-->

templates/includes/footer.html
{% load static %}
<div class="footer">
    <div class="footer-content">
        <div class="footer-section about footer-box">
            <h3 class="footer-text">Genç Girişimciler Kulübü</h3>
            <br>
            <p class="footer-text">Sabancı Üniversitesi
                Orta Mahallesi
                No:27 34956 Tuzla / İstanbul</p>
            <p>ggk@sabanciuniv.edu</p>
        </div>
        <div class="footer-section questions footer-box">
            <h3 class="footer-text">Sıkça Sorulan Sorular</h3>
            <br>
            <ul class="question-list">
                <li class="list-item">GGK nedir?</li>
                <li class="list-item">Bizimle nasıl çalışabilirsiniz?</li>
                <li class="list-item">Etkinliklerimize nasıl katılabilirsiniz?</li>
            </ul>
        </div>
        <div class="footer-section events footer-box">
            <h3 class="footer-text">Yakın Etkinlikler</h3>
            <br>
            <ul class="question-list">
                {% if events %}
                    {% for event in events %}
                        {% if event.distinct_page %}
                            <a href="{{event.distinct_page}}"><li class="list-item">{{event.title}}</li></a>
                        {% else %}
                            <a href="/events/{{event.id}}"><li class="list-item">{{event.title}}</li></a>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <p>Henüz yaklaşan bir etkinlik yok</p>
                {% endif %}
            </ul>
            <br>
        </div>
    </div>
    <div class="footer-bottom">
        <p class="bottom-text">Sabancı Üniversitesi | Genç Girişimciler Kulübü | 2020</p>
    </div>
</div>

templates/includes/header.html
{% load static %}
<style>
    .navbar-custom{
        background-color:black;
    }

    .nav-link{
        color:whitesmoke !important;
        font: SourceSans !important;
    }
</style>

<div class="jumbotron header">
    <div class="header-option"><h3><a href="/events/{{event.id}}">{{event.title}}</a></h3></div>
    {% if mainsponsors %}
    <div class="header-option"><h3><a href="/events/{{event.id}}/sponsors">Sponsorlarımız</a></h3></div>
    {% else %}
        {% if goldsponsors %}
            <div class="header-option"><h3><a href="/events/{{event.id}}/sponsors">Sponsorlarımız</a></h3></div>
        {% else %}
            {% if silversponsors %}
                <div class="header-option"><h3><a href="/events/{{event.id}}/sponsors">Sponsorlarımız</a></h3></div>
            {% else %}
                {% if bronzesponsors %}
                    <div class="header-option"><h3><a href="/events/{{event.id}}/sponsors">Sponsorlarımız</a></h3></div>
                {% else %}
                    {% if itemsponsors %}
                        <div class="header-option"><h3><a href="/events/{{event.id}}/sponsors">Sponsorlarımız</a></h3></div>
                    {% else %}
                    {% endif %}
                {% endif %}
            {% endif %}
        {% endif %}
    {% endif %}
    <div class="header-option"><h3><a href="/events/{{event.id}}/speakers">Konuşmacılarımız</a></h3></div>
    <div class="header-option"><h3><a href="/events/{{event.id}}/join">Katıl</a></h3></div>
</div>

templates/includes/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<nav class="navbar navbarCollapse navbar-toggleable-md navbar-inverse fixed-top  navbar-custom">
    <br>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">

        <ul class="navbar-nav mr-auto">
          <a class="navbar-brand" href="{% url 'index' %}"><img class = "logo" src="{% static 'images/GGK_logo-2.png' %}"></a>
          <li class="nav-item mobile-nav-item">
            <br>
          </li>
          <li class="nav-item mobile-nav-item">
            <a class="nav-link" href="{% url 'index' %}">Anasayfa</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contacts:new member' %}">Üye Ol</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contacts:contact' %}">İletişim</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'event:events' %}">Etkinliklerimiz</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'article:blog' %}">Blog</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'article:dashboard' %}" class="nav-link">Kullanıcı Kontrol Paneli</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'article:logout' %}" class="nav-link">Çıkış Yap</a>
          </li>
          {% endif %}
        </ul>
      <div class="desktop-nav-item">
        <ul class="navbar-nav ml-auto">
            
            {% if request.user.is_authenticated %}
            <li class="nav-item" id="navbar-user-active-1">
              <a class="nav-link px-2 custom-icon" href="#"><i class="fa fa-twitter"></i></a>
            </li>
            <li class="nav-item" id="navbar-user-active-2">
              <a class="nav-link px-2 custom-icon" href="#"><i class="fa fa-instagram"></i></a>
            </li>
            <li class="nav-item" id="navbar-user-active-3">
              <a class="nav-link px-2 custom-icon" href="#"><i class="fa fa-linkedin"></i></a>
            </li>
            <li class="nav-item" id="navbar-user-option-1">
              <a href="{% url 'article:dashboard' %}" class="nav-link">{{request.user.username}}</a>
            </li>
            <li class="nav-item" id="navbar-user-option-2">
              <a href="{% url 'article:logout' %}" class="nav-link">Çıkış</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link px-2 custom-icon" href="https://twitter.com/su_ggk"><i class="fa fa-twitter"></i></a>
            </li>
            <li class="nav-item">
              <a class="nav-link px-2 custom-icon" href="https://www.instagram.com/sabanciggk"><i class="fa fa-instagram"></i></a>
            </li>
            <li class="nav-item">
              <a class="nav-link px-2 custom-icon" href="https://www.linkedin.com/company/18221543"><i class="fa fa-linkedin"></i></a>
            </li>
            {% endif %}
        </ul>
      </div>
      </ul>
    </div>
  </nav>